### ISSUE TITLE
DeprecationWarning & "Must use python 3.9 or newer"

### ISSUE THREAD

**Issue by mqxb9527** [ZikeYan/activeINR#3]
Thanks for your great work! I ran into a tricky problem while trying to reproduce your system:

" setup.py:441: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  assert StrictVersion(
setup.py:443: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  ) >= StrictVersion("3.9"), "Must use python 3.9 or newer"
Traceback (most recent call last):
  File "setup.py", line 441, in <module>
    assert StrictVersion(
AssertionError: Must use python 3.9 or newer "

I have tried many ways, but I still can't solve this problem. Is there a chance you could help me solve it?  I'll be very greatful.

Hope for your reply, best wishes!

**Comment by ZikeYan** [comment]
> Thanks for your great work! I ran into a tricky problem while trying to reproduce your system:
> 
> " setup.py:441: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead. assert StrictVersion( setup.py:443: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead. ) >= StrictVersion("3.9"), "Must use python 3.9 or newer" Traceback (most recent call last): File "setup.py", line 441, in assert StrictVersion( AssertionError: Must use python 3.9 or newer "
> 
> I have tried many ways, but I still can't solve this problem. Is there a chance you could help me solve it? I'll be very greatful.
> 
> Hope for your reply, best wishes!

Hi, thanks for you interest in our work. Did you checkout to the right version (git checkout tags/v0.1.7) for Habitat-sim and Habitat-lab when building the simulation environment?

**Comment by mqxb9527** [comment]
> > Thanks for your great work! I ran into a tricky problem while trying to reproduce your system:
> > " setup.py:441: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead. assert StrictVersion( setup.py:443: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead. ) >= StrictVersion("3.9"), "Must use python 3.9 or newer" Traceback (most recent call last): File "setup.py", line 441, in assert StrictVersion( AssertionError: Must use python 3.9 or newer "
> > I have tried many ways, but I still can't solve this problem. Is there a chance you could help me solve it? I'll be very greatful.
> > Hope for your reply, best wishes!
> 
> Hi, thanks for you interest in our work. Did you checkout to the right version (git checkout tags/v0.1.7) for Habitat-sim and Habitat-lab when building the simulation environment?

Thank you for your instruction. I'll install the package of v0.1.7 and try to reproduce this work again.

**Comment by Mqxb9527** [comment]
> > Thanks for your great work! I ran into a tricky problem while trying to reproduce your system:
> > " setup.py:441: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead. assert StrictVersion( setup.py:443: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead. ) >= StrictVersion("3.9"), "Must use python 3.9 or newer" Traceback (most recent call last): File "setup.py", line 441, in assert StrictVersion( AssertionError: Must use python 3.9 or newer "
> > I have tried many ways, but I still can't solve this problem. Is there a chance you could help me solve it? I'll be very greatful.
> > Hope for your reply, best wishes!
> 
> Hi, thanks for you interest in our work. Did you checkout to the right version (git checkout tags/v0.1.7) for Habitat-sim and Habitat-lab when building the simulation environment?

Hi, sorry to bother you again. I downloaded the package which version is v0.1.7 of habitat-lab and habitat-sim. But when I run this code: 
"cd habitat-sim && python setup.py install --with-cuda"
the version of habitat-sim will be update to the lastest one which need the python3.9, then the error occurered: 
“
…
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find PythonInterp: Found unsuitable version "3.8.5", but required
  is at least "3.9" (found /home/aslam/anaconda3/envs/activeINR/bin/python)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:391 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindPythonInterp.cmake:169 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/dependencies.cmake:132 (find_package)
  CMakeLists.txt:148 (include)


-- Configuring incomplete, errors occurred!
See also "/home/aslam/ANM/activeINR/habitat-sim/build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 374, in <module>
    
  File "/home/aslam/anaconda3/envs/activeINR/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/aslam/anaconda3/envs/activeINR/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 177, in setup
    return run_commands(dist)
  File "/home/aslam/anaconda3/envs/activeINR/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
    dist.run_commands()
  File "/home/aslam/anaconda3/envs/activeINR/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/home/aslam/anaconda3/envs/activeINR/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/aslam/anaconda3/envs/activeINR/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/aslam/anaconda3/envs/activeINR/lib/python3.8/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/aslam/anaconda3/envs/activeINR/lib/python3.8/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/aslam/anaconda3/envs/activeINR/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
    self.distribution.run_command(command)
  File "/home/aslam/anaconda3/envs/activeINR/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/aslam/anaconda3/envs/activeINR/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/aslam/anaconda3/envs/activeINR/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/aslam/anaconda3/envs/activeINR/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/home/aslam/anaconda3/envs/activeINR/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
    self.distribution.run_command(command)
  File "/home/aslam/anaconda3/envs/activeINR/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/aslam/anaconda3/envs/activeINR/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/aslam/anaconda3/envs/activeINR/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/aslam/anaconda3/envs/activeINR/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/home/aslam/anaconda3/envs/activeINR/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
    self.distribution.run_command(command)
  File "/home/aslam/anaconda3/envs/activeINR/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/aslam/anaconda3/envs/activeINR/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "setup.py", line 204, in run
    class CMakeExtension(Extension):
  File "setup.py", line 268, in build_extension
    extdir = os.path.abspath(os.path.dirname(self.get_ext_fullpath(ext.name)))
  File "/home/aslam/anaconda3/envs/activeINR/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-H/home/aslam/ANM/activeINR/habitat-sim/src', '-Bbuild', '-DBUILD_PYTHON_BINDINGS=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/aslam/ANM/activeINR/habitat-sim/build/lib.linux-x86_64-cpython-38/habitat_sim/_ext', '-DPYTHON_EXECUTABLE=/home/aslam/anaconda3/envs/activeINR/bin/python', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DBUILD_GUI_VIEWERS=ON', '-DTARGET_HEADLESS=OFF', '-DBUILD_TEST=OFF', '-DBUILD_WITH_BULLET=OFF', '-DBUILD_DATATOOL=OFF', '-DBUILD_WITH_CUDA=ON']' returned non-zero exit status 1.
”

Before I executed that command, setup.py had python>=3.6, but after executing it, it automatically became python>=3.9. I don't know how to solve this problem. 

Could you help me one more time? Thank you very much !!!
